# Form implementation generated from reading ui file 'enter.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mebel(object):
    def setupUi(self, Mebel):
        Mebel.setObjectName("Mebel")
        Mebel.resize(610, 396)
        Mebel.setStyleSheet("background-color: rgb(255, 255, 235);")
        self.centralwidget = QtWidgets.QWidget(parent=Mebel)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonProduct = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonProduct.setGeometry(QtCore.QRect(240, 80, 151, 41))
        self.ButtonProduct.setStyleSheet("background-color: rgb(255, 255, 207);")
        self.ButtonProduct.setObjectName("ButtonProduct")
        self.ButtonCeh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ButtonCeh.setGeometry(QtCore.QRect(240, 220, 151, 41))
        self.ButtonCeh.setStyleSheet("background-color: rgb(255, 255, 207);")
        self.ButtonCeh.setObjectName("ButtonCeh")
        Mebel.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Mebel)
        self.statusbar.setObjectName("statusbar")
        Mebel.setStatusBar(self.statusbar)

        self.retranslateUi(Mebel)
        QtCore.QMetaObject.connectSlotsByName(Mebel)

    def retranslateUi(self, Mebel):
        _translate = QtCore.QCoreApplication.translate
        Mebel.setWindowTitle(_translate("Mebel", "Мебель"))
        self.ButtonProduct.setText(_translate("Mebel", "Продукты"))
        self.ButtonCeh.setText(_translate("Mebel", "Цех"))
