# Form implementation generated from reading ui file 'product.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Mebel2(object):
    def setupUi(self, Mebel):
        Mebel.setObjectName("Mebel")
        Mebel.resize(610, 396)
        Mebel.setStyleSheet("background-color: rgb(255, 255, 235);")
        self.centralwidget = QtWidgets.QWidget(parent=Mebel)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.BackButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 75, 24))
        self.BackButton.setObjectName("BackButton")
        self.CehButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CehButton.setGeometry(QtCore.QRect(520, 10, 75, 24))
        self.CehButton.setObjectName("CehButton")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 60, 571, 211))
        self.tableView.setObjectName("tableView")
        self.AddButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(50, 310, 75, 24))
        self.AddButton.setObjectName("AddButton")
        self.DelButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DelButton.setGeometry(QtCore.QRect(270, 310, 75, 24))
        self.DelButton.setObjectName("DelButton")
        self.EditButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.EditButton.setGeometry(QtCore.QRect(474, 310, 101, 24))
        self.EditButton.setObjectName("EditButton")
        Mebel.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Mebel)
        self.statusbar.setObjectName("statusbar")
        Mebel.setStatusBar(self.statusbar)

        self.retranslateUi(Mebel)
        QtCore.QMetaObject.connectSlotsByName(Mebel)

    def retranslateUi(self, Mebel):
        _translate = QtCore.QCoreApplication.translate
        Mebel.setWindowTitle(_translate("Mebel", "Мебель"))
        self.label.setText(_translate("Mebel", "ПРОДУКТЫ"))
        self.BackButton.setText(_translate("Mebel", "Назад"))
        self.CehButton.setText(_translate("Mebel", "Цех"))
        self.AddButton.setText(_translate("Mebel", "Добавить"))
        self.DelButton.setText(_translate("Mebel", "Удалить"))
        self.EditButton.setText(_translate("Mebel", "Редактировать"))
